# 05-scheduler-rbac.yaml
# Configures permissions for the scheduler service account.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helios-scheduler-sa # The Service Account the scheduler Deployment will use
  namespace: helios
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager-role # Defines permissions needed by the scheduler
  namespace: helios
rules:
  # Allow managing (create, get, list, watch, delete) Job resources
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "watch", "list", "delete"]
  # Allow getting Pods (to find Job pods) and reading logs
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding # Binds the Role to the Service Account
  namespace: helios
subjects:
  # The identity being granted permissions
  - kind: ServiceAccount
    name: helios-scheduler-sa
    namespace: helios
roleRef:
  # The permissions being granted
  kind: Role
  name: job-manager-role
  apiGroup: rbac.authorization.k8s.io